# PostgreSQL configuration for local development
[postgresql]
host = "localhost"
user = "postgres"
password = "your_password_here"
database = "ECOM"
port = "5432"

# For NeonDB deployment, you can also use:
# [postgresql]
# host = "your-neon-hostname.neon.tech"
# user = "your-neon-username"
# password = "your-neon-password"
# database = "your-database-name"
# port = "5432"
