# NeonDB PostgreSQL Configuration
DATABASE_URL = "postgresql://neondb_owner:npg_EZ0FVkaeyv4t@ep-aged-salad-afq5e4ty-pooler.c-2.us-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"

[postgresql]
host = "ep-aged-salad-afq5e4ty-pooler.c-2.us-west-2.aws.neon.tech"
user = "neondb_owner"
password = "npg_EZ0FVkaeyv4t"
database = "neondb"
port = "5432"
sslmode = "require"

[connections.neon]
url = "postgresql://neondb_owner:npg_EZ0FVkaeyv4t@ep-aged-salad-afq5e4ty-pooler.c-2.us-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"

# For local PostgreSQL development (if needed)
# [postgresql_local] 
# host = "localhost"
# user = "postgres"
# password = "your_local_password"
# database = "ECOM"
# port = "5432"